server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      format_sql: true
      show-sql: true

logging:
  level:
    com:
      bookshop: INFO
    org:
      springframework: ERROR
