spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bookshopDb
    username: root
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
