spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/appDb
    username: myUser
    password: myUser
  jpa:
    hibernate:
      ddl-auto: update
