spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/appDb
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

